# Site settings
title: Bicicletta
email: DEGoodmanWilson@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  An open source iOS / Android interface for your electric bicycle.
baseurl: "/bicicletta" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: DEGoodmanWilson
github_username:  DEGoodmanWilson

# Build settings
markdown: kramdown
highlighter: pygments

collections:
  modules:
    output: true
